name: todo_list_app
description: "A simple To-Do List Flutter app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  path: ^1.9.1
  go_router: ^15.1.1
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
